# ---------- Stage 1 : Build React ----------
FROM node:16 AS builder

WORKDIR /app

COPY react_client/package*.json ./

RUN npm install

COPY react_client/ .

RUN npm run build


# ---------- Stage 2 : Nginx ----------
FROM nginx:latest

COPY nginx/nginx.prod.conf /etc/nginx/nginx.conf

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]