# Generated by Django 4.0.3 on 2026-07-10 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200)),
                ('is_patient', models.BooleanField()),
                ('is_doctor', models.BooleanField()),
                ('tc', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorPatientAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_email', models.EmailField(max_length=50)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_email', models.EmailField(max_length=50)),
                ('problem', models.CharField(max_length=50)),
                ('fees', models.IntegerField()),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('doctor_email', models.EmailField(max_length=50)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_email', models.EmailField(max_length=50)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'is_doctor': True}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('doctor_image', models.ImageField(upload_to='doctorimg')),
                ('study', models.CharField(max_length=50)),
                ('specialist', models.CharField(max_length=50)),
                ('experience', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('avail_time_start', models.TimeField()),
                ('avail_time_end', models.TimeField()),
                ('about', models.TextField()),
            ],
        ),
    ]
